### PR TITLE
Initial implementation

### PR DESCRIPTION
**Pull request by 3lvis**
Initial implementation

``` objc
NSDictionary *dictionary = @{@"first_name" : @"Chris",
                             @"contacts[0].name" : @"Tim",
                             @"contacts[0].phone_number" : @"444444",
                             @"contacts[1].name" : @"Johannes",
                             @"contacts[1].phone_number" : @"555555"};


NSDictionary *nestedAttributesDictionary = [dictionary hyp_nestify];

/*
"first_name": "Chris",
"contacts_attributes": [
  {
    "0": {
      "name": "Tim",
      "phone_number": "444444"
    },
    "1": {
      "name": "Johannes",
      "phone_number": "555555"
    }
  }
]
*/
```

### CODE REVIEW

**Comment by 3lvis** [comment]
wait

**Comment by kostiakoval** [comment]
))

**Comment by kostiakoval** [comment]
I can't merge it, No merge button :( 
screen shot 2015-03-19 at 11 21 17

**Comment by 3lvis** [comment]
ohhh

**Pull request merged**
